PHILOSOPHICAL_NEW = [
    {"text": "Act as if what you do makes a difference. It does.", "author": "William James"},
    {"text": "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.", "author": "William James"},
    {"text": "Believe that life is worth living and your belief will help create the fact.", "author": "William James"},
    {"text": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson"},
    {"text": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "author": "Ralph Waldo Emerson"},
    {"text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson"},
    {"text": "Knowing yourself is the beginning of all wisdom.", "author": "Aristotle"},
    {"text": "Happiness depends upon ourselves.", "author": "Aristotle"},
    {"text": "It is the mark of an educated mind to be able to entertain a thought without accepting it.", "author": "Aristotle"},
    {"text": "Science is organized knowledge. Wisdom is organized life.", "author": "Immanuel Kant"},
    {"text": "Dare to know! Have the courage to use your own understanding.", "author": "Immanuel Kant"},
    {"text": "In law a man is guilty when he violates the rights of others. In ethics he is guilty if he only thinks of doing so.", "author": "Immanuel Kant"},
    {"text": "He who has a why to live can bear almost any how.", "author": "Friedrich Nietzsche"},
    {"text": "That which does not kill us makes us stronger.", "author": "Friedrich Nietzsche"},
    {"text": "There are no facts, only interpretations.", "author": "Friedrich Nietzsche"},
    {"text": "I think, therefore I am.", "author": "Rene Descartes"},
    {"text": "It is not enough to have a good mind; the main thing is to use it well.", "author": "Rene Descartes"},
    {"text": "Doubt is the origin of wisdom.", "author": "Rene Descartes"},
    {"text": "Reason is, and ought only to be the slave of the passions.", "author": "David Hume"},
    {"text": "Beauty in things exists merely in the mind which contemplates them.", "author": "David Hume"},
    {"text": "Generally speaking, the errors in religion are dangerous; those in philosophy only ridiculous.", "author": "David Hume"},
    {"text": "Compassion is the basis of morality.", "author": "Arthur Schopenhauer"},
    {"text": "Man can do what he wills but he cannot will what he wills.", "author": "Arthur Schopenhauer"},
    {"text": "In the depth of winter, I finally learned that within me there lay an invincible summer.", "author": "Albert Camus"},
    {"text": "Real generosity toward the future lies in giving all to the present.", "author": "Albert Camus"},
]

