UPLIFTING_BACKFILL = [
    {"text": "If you want others to be happy, practice compassion. If you want to be happy, practice compassion.", "author": "Dalai Lama"},
    {"text": "Just one small positive thought in the morning can change your whole day.", "author": "Dalai Lama"},
    {"text": "Calm mind brings inner strength and self-confidence.", "author": "Dalai Lama"},
    {"text": "Share your knowledge. It is a way to achieve immortality.", "author": "Dalai Lama"},
    {"text": "There is no way to happiness. Happiness is the way.", "author": "Thich Nhat Hanh"},
    {"text": "Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy.", "author": "Thich Nhat Hanh"},
    {"text": "Breathing in, I calm body and mind. Breathing out, I smile.", "author": "Thich Nhat Hanh"},
    {"text": "The most precious gift we can offer anyone is our attention.", "author": "Thich Nhat Hanh"},
    {"text": "When you do things from your soul, you feel a river moving in you, a joy.", "author": "Rumi"},
    {"text": "Try not to resist life's changes. Let life flow through you.", "author": "Rumi"},
    {"text": "You were born with wings, why prefer to crawl through life?", "author": "Rumi"},
    {"text": "Let the beauty of what you love be what you do.", "author": "Rumi"},
    {"text": "No one can make you feel inferior without your consent.", "author": "Eleanor Roosevelt"},
    {"text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt"},
    {"text": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt"},
    {"text": "With the new day comes new strength and new thoughts.", "author": "Eleanor Roosevelt"},
    {"text": "You must do the thing you think you cannot do.", "author": "Eleanor Roosevelt"},
    {"text": "Turn your wounds into wisdom.", "author": "Oprah Winfrey"},
    {"text": "The biggest adventure you can take is to live the life of your dreams.", "author": "Oprah Winfrey"},
    {"text": "Doing the best at this moment puts you in the best place for the next moment.", "author": "Oprah Winfrey"},
    {"text": "The more you praise and celebrate your life, the more there is in life to celebrate.", "author": "Oprah Winfrey"},
    {"text": "Think like a queen. A queen is not afraid to fail.", "author": "Oprah Winfrey"},
    {"text": "Hope begins in the dark, the stubborn hope that if you just show up and try, the dawn will come.", "author": "Anne Lamott"},
    {"text": "Almost everything will work again if you unplug it for a few minutes, including you.", "author": "Anne Lamott"},
    {"text": "Lighthouses do not go running all over an island for boats to save; they just stand there shining.", "author": "Anne Lamott"},
    {"text": "Joy is the best makeup.", "author": "Anne Lamott"},
    {"text": "Perfection is the voice of the oppressor.", "author": "Anne Lamott"},
    {"text": "Nothing ever goes away until it has taught us what we need to know.", "author": "Pema Chodron"},
    {"text": "You are the sky. Everything else is just the weather.", "author": "Pema Chodron"},
    {"text": "Compassion for others begins with kindness to ourselves.", "author": "Pema Chodron"},
    {"text": "The most difficult times for many of us are the ones we give ourselves.", "author": "Pema Chodron"},
    {"text": "We work on ourselves in order to help others, but also we help others in order to work on ourselves.", "author": "Pema Chodron"},
    {"text": "Imperfections are not inadequacies; they are reminders that we are all in this together.", "author": "Brene Brown"},
    {"text": "Talk to yourself like you would to someone you love.", "author": "Brene Brown"},
    {"text": "Courage starts with showing up and letting ourselves be seen.", "author": "Brene Brown"},
    {"text": "Owning our story can be hard but not nearly as difficult as spending our lives running from it.", "author": "Brene Brown"},
    {"text": "Vulnerability is the birthplace of innovation, creativity and change.", "author": "Brene Brown"},
    {"text": "I am in the right place, at the right time, doing the right thing.", "author": "Louise Hay"},
    {"text": "Every thought we think is creating our future.", "author": "Louise Hay"},
    {"text": "I forgive myself and set myself free.", "author": "Louise Hay"},
    {"text": "Life loves you.", "author": "Louise Hay"},
    {"text": "As I say yes to life, life says yes to me.", "author": "Louise Hay"},
    {"text": "Try to be a rainbow in someone's cloud.", "author": "Maya Angelou"},
    {"text": "Nothing can dim the light which shines from within.", "author": "Maya Angelou"},
    {"text": "You alone are enough. You have nothing to prove to anybody.", "author": "Maya Angelou"},
    {"text": "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through.", "author": "Maya Angelou"},
    {"text": "Success is liking yourself, liking what you do, and liking how you do it.", "author": "Maya Angelou"},
    {"text": "The best way out is always through.", "author": "Robert Frost"},
    {"text": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost"},
    {"text": "Happiness makes up in height for what it lacks in length.", "author": "Robert Frost"},
    {"text": "Freedom lies in being bold.", "author": "Robert Frost"},
    {"text": "When we are no longer able to change a situation, we are challenged to change ourselves.", "author": "Viktor Frankl"},
    {"text": "Between stimulus and response there is a space. In that space is our power to choose our response.", "author": "Viktor Frankl"},
    {"text": "What is to give light must endure burning.", "author": "Viktor Frankl"},
    {"text": "Life is never made unbearable by circumstances, but only by lack of meaning and purpose.", "author": "Viktor Frankl"},
    {"text": "The privilege of a lifetime is to become who you truly are.", "author": "Carl Jung"},
    {"text": "I am not what happened to me, I am what I choose to become.", "author": "Carl Jung"},
    {"text": "Your visions will become clear only when you can look into your own heart.", "author": "Carl Jung"},
    {"text": "Who looks outside, dreams; who looks inside, awakes.", "author": "Carl Jung"},
    {"text": "Know all the theories, master all the techniques, but as you touch a human soul be just another human soul.", "author": "Carl Jung"},
    {"text": "Wherever you are, and whatever you do, be in love.", "author": "Rumi"},
    {"text": "Raise your words, not your voice. It is rain that grows flowers, not thunder.", "author": "Rumi"},
    {"text": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe"},
    {"text": "Success is a journey, not a destination.", "author": "Arthur Ashe"},
    {"text": "One important key to success is self-confidence. An important key to self-confidence is preparation.", "author": "Arthur Ashe"},
    {"text": "From what we get, we can make a living; what we give, however, makes a life.", "author": "Arthur Ashe"},
    {"text": "Clarity and simplicity are the antidotes to complexity and uncertainty.", "author": "General George Casey"},
    {"text": "Your calm mind is the ultimate weapon against your challenges.", "author": "Bryant McGill"},
    {"text": "There is no greater agony than bearing an untold story inside you.", "author": "Maya Angelou"},
    {"text": "Caring for myself is not self-indulgence, it is self-preservation.", "author": "Audre Lorde"},
    {"text": "Hope is being able to see that there is light despite all of the darkness.", "author": "Desmond Tutu"},
    {"text": "Live quietly in the moment and see the beauty of all before you.", "author": "Paramahansa Yogananda"},
    {"text": "The season of failure is the best time for sowing the seeds of success.", "author": "Paramahansa Yogananda"},
    {"text": "Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.", "author": "Deepak Chopra"},
    {"text": "The best way to capture moments is to pay attention.", "author": "Jon Kabat-Zinn"},
    {"text": "Mindfulness means being awake. It means knowing what you are doing.", "author": "Jon Kabat-Zinn"},
    {"text": "A journey of a thousand miles begins with a single step.", "author": "Chinese proverb"},
    {"text": "Fall seven times, stand up eight.", "author": "Chinese proverb"},
    {"text": "Kindness is a language which the deaf can hear and the blind can see.", "author": "Mark Twain"},
    {"text": "The secret of getting ahead is getting started.", "author": "Mark Twain"},
    {"text": "Courage is resistance to fear, mastery of fear, not absence of fear.", "author": "Mark Twain"},
    {"text": "Learning never exhausts the mind.", "author": "Leonardo da Vinci"},
    {"text": "Nothing can be loved or hated unless it is first understood.", "author": "Leonardo da Vinci"},
    {"text": "One day at a time is all we do. One day at a time is good enough.", "author": "Anne Lamott"},
    {"text": "We are all just walking each other home.", "author": "Ram Dass"},
    {"text": "Be here now.", "author": "Ram Dass"},
    {"text": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa"},
    {"text": "Peace begins with a smile.", "author": "Mother Teresa"},
    {"text": "If you judge people, you have no time to love them.", "author": "Mother Teresa"},
    {"text": "All our dreams can come true, if we have the courage to pursue them.", "author": "Walt Disney"},
    {"text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
    {"text": "Never doubt that a small group of thoughtful, committed citizens can change the world.", "author": "Margaret Mead"},
    {"text": "Always remember that you are absolutely unique. Just like everyone else.", "author": "Margaret Mead"},
    {"text": "One ought, every day at least, to hear a little song, read a good poem, see a fine picture, and, if it were possible, to speak a few reasonable words.", "author": "Johann Wolfgang von Goethe"},
    {"text": "As soon as you trust yourself, you will know how to live.", "author": "Johann Wolfgang von Goethe"},
    {"text": "Within you there is a stillness and a sanctuary to which you can retreat at any time.", "author": "Hermann Hesse"},
    {"text": "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, I will try again tomorrow.", "author": "Mary Anne Radmacher"},
]

